# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Suraj\LearningPath\Python GUI Projects\PyQt5 From A-Z 2020-9\9. Visually designing GUI's with QtDesigner\Code\ui\example-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMain(object):
    def setupUi(self, DialogMain):
        DialogMain.setObjectName("DialogMain")
        DialogMain.resize(551, 378)
        self.grbDialog = QtWidgets.QGroupBox(DialogMain)
        self.grbDialog.setEnabled(True)
        self.grbDialog.setGeometry(QtCore.QRect(10, 10, 531, 231))
        self.grbDialog.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.grbDialog.setCheckable(False)
        self.grbDialog.setChecked(False)
        self.grbDialog.setObjectName("grbDialog")
        self.lbl1 = QtWidgets.QLabel(self.grbDialog)
        self.lbl1.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.lbl1.setObjectName("lbl1")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.grbDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 70, 194, 22))
        self.dateTimeEdit.setWrapping(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.grbDialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 110, 160, 22))
        self.horizontalSlider.setMaximum(999)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.listWidget = QtWidgets.QListWidget(self.grbDialog)
        self.listWidget.setGeometry(QtCore.QRect(260, 30, 256, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lcdNumber = QtWidgets.QLCDNumber(self.grbDialog)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 150, 181, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit = QtWidgets.QLineEdit(DialogMain)
        self.lineEdit.setGeometry(QtCore.QRect(10, 260, 521, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(DialogMain)
        self.label.setGeometry(QtCore.QRect(20, 310, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(DialogMain)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber.display) # type: ignore
        self.lineEdit.textChanged['QString'].connect(self.label.setText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogMain)

    def retranslateUi(self, DialogMain):
        _translate = QtCore.QCoreApplication.translate
        DialogMain.setWindowTitle(_translate("DialogMain", "My GUI"))
        self.grbDialog.setTitle(_translate("DialogMain", "My Gui Widget"))
        self.lbl1.setText(_translate("DialogMain", "First Widget"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("DialogMain", "Item-1"))
        item = self.listWidget.item(1)
        item.setText(_translate("DialogMain", "Item-2"))
        item = self.listWidget.item(2)
        item.setText(_translate("DialogMain", "Item-3"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setPlaceholderText(_translate("DialogMain", "Type something here"))
